<?php

return [
    'roles_and_permissions' => [
        'Super Admin' => [
            'full_access',
            'create_users',
            'edit_users',
            'deactivate_users',
            'delete_users',
            'assign_roles',
            'modify_roles',
            'manage_question_banks',
            'manage_questions',
            'access_reports',
            'access_analytics',
            'access_system_logs',
            'perform_backups',
            'restore_backups',
            'send_notifications',
            'monitor_login_activities',
            'manage_security_settings',
            'create_custom_roles',
            'create_custom_permissions',
            'override_restrictions',
        ],
        'Admin' => [
            'manage_users',
            'assign_roles',
            'create_question_banks',
            'organize_question_banks',
            'review_questions',
            'approve_questions',
            'generate_reports',
            'perform_backups',
            'send_notifications',
            'access_security_settings',
            'access_activity_logs',
        ],
        'Group Admin' => [
            'manage_group_users',
            'assign_group_roles',
            'create_group_question_banks',
            'organize_group_question_banks',
            'review_group_questions',
            'approve_group_questions',
            'generate_group_reports',
            'create_tests',
            'schedule_tests',
            'send_group_notifications',
        ],
        'Content Manager' => [
            'add_questions',
            'edit_questions',
            'delete_questions',
            'create_question_banks',
            'organize_question_banks',
            'review_questions',
            'approve_questions',
            'import_questions',
            'export_questions',
            'access_question_reports',
            'access_bank_reports',
        ],
        'Teacher' => [
            'create_question_banks',
            'manage_question_banks',
            'add_questions',
            'edit_questions',
            'organize_questions',
            'assign_tests',
            'monitor_student_progress',
            'view_student_reports',
            'view_content_reports',
        ],
        'Teacher Assistant' => [
            'support_teachers',
            'manage_question_banks',
            'create_content',
            'organize_content',
            'prepare_tests',
            'schedule_tests',
            'monitor_student_progress',
            'send_notifications',
        ],
        'Student' => [
            'access_tests',
            'view_grades',
            'review_test_answers',
            'submit_feedback',
        ],
        'Reviewer' => [
            'review_questions',
            'provide_feedback',
            'approve_questions',
            'reject_questions',
        ],
        'Technical Support' => [
            'manage_user_access',
            'troubleshoot_login_issues',
            'resolve_technical_issues',
            'manage_error_logs',
            'send_notifications',
            'perform_system_maintenance',
            'perform_backups',
        ],
    ],
];